### ISSUE TITLE
Use Supervisor client from edge

### ISSUE THREAD

**Issue by mma-mm** [Azure/azure-iiot-opc-ua#4]
Hi,

i'd like to use the SupervisorClient from an EdgeModule. While this works in the online case, this does not work in the offline case (at least not with iotedgehubdev). Is there a way to tell the SupervisorClient to call the methods of the azure-iiot-opc-twin-module via the EdgeHub instead of the IoTHub?

Best regards

Matthias Mucha

**Comment by marcschier** [comment]
Hi @mma-mm, 

this is an interesting use case.  

It should be straightforward, the code was build to be composable.  ActivationClient and SupervisorClient depend on IMethodClient.  IMethodClient is implemented in ChunkMethodClient, which you need to inject using Autofac DI in your module.   This has the benefit of being able to go beyond the size limits of method payload.   

ChunkMethodClient in turn uses IJsonMethodClient, which is implemented by ModuleHost (which will use ModuleClient if run in iot edge context and thus use edgehub and is available in offline).  So presuming you use ModuleHost in your module already, all SupervisorClient services should be useable to you in your module.   If you decide against ModuleHost, you need to provide an implementation of the one or two methods in IJsonMethodClient, should be pretty straightforward to layer that over ModuleClient.

Another interesting idea for "offline" would be to also bring in the ASP.net core controller(s) and expose the cloud REST api at the edge, thus being able to move the same insights->actions loop that runs in the cloud to the edge.   

As I said, happy to take contributions of this nature, in particular as we would eventually want to add something similar :-)

Best regards,

Marc

**Comment by mma-mm** [comment]
It works, thank you!
